### PR TITLE
Tradução inicial do artigo

### PR DESCRIPTION
**Pull request by thdotnet**
Tradução inicial do artigo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thdotnet__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by SunnyDeng** [comment]
@thdotnet, I am seeing you closed this PR 3 hours ago. If the feedback is still valid, please sign the CLA as the Azure bot remind you. We will look into the change and merge it. 
Thanks
Sunny @MS

**Comment by thdotnet** [comment]
Hi @SunnyDeng I've created a new pull request. https://github.com/Azure/azure-content-ptbr/pull/29

**Comment by thdotnet** [comment]
and I already signed the CLA.

**Pull request closed without merging**
